version: '2'
services:
  api:
    build:
        context: ./honeybee-server
        dockerfile: Dockerfile
    image: ladybugtools/hbserver
    command: "python app.py"
    # restart: always
    ports:
        - "${PORT}:${PORT}"
    links:
        - redis
        - worker
    volumes:
        - ./jobs:/usr/local/hb_jobs
    environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        - C_FORCE_ROOT=${C_FORCE_ROOT}
        - HOST=${HOST}
        - PORT=${PORT}
        - DEBUG=${DEBUG}

  worker:
    build:
        context: ./honeybee-worker
        dockerfile: Dockerfile
    image: ladybugtools/hbworker
    links:
        - redis
    volumes:
        - ./jobs:/usr/local/hb_jobs
    environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        - C_FORCE_ROOT=${C_FORCE_ROOT}

  monitor:
    image: ladybugtools/hbworker
    ports:
        - "${MONITOR_PORT}:${MONITOR_PORT}"
    entrypoint: flower
    command: -A tasks --port=${MONITOR_PORT} --broker=${CELERY_BROKER_URL}
    links:
        - redis

  redis:
    image: redis
